Description of FindListCard
Home > Mateda2.0 > otherfiles > FindListCard.m
FindListCard
PURPOSE
[ListFactorsCard] = FindListCard(ListFactors,Card)
SYNOPSIS
function [ListFactorsCard] = FindListCard(ListFactors,Card)
DESCRIPTION
 [ListFactorsCard] = FindListCard(ListFactors,Card)
 FindListCard:  For each factor of variables gives the corresponding
                accumulate cardinality
 INPUT:
 ListFactors: Each  cell  {i} stores the variables in the factor
 Card: Cardinality of the variables
 OUTPUT:
 ListFactorsCard: For each factor of variables stores the corresponding
                  accumulate cardinality
 Last version 8/26/2008. Roberto Santana (roberto.santana@ehu.es)
CROSS-REFERENCE INFORMATION
This function calls:
FindAccCard [AccCard] = FindAccCard(length,Card)
This function is called by:
BN_Prediction EXAMPLE 2: Evaluation of the prediction capability of the models
DefaultEDA_NKRandom EXAMPLE 9: Bayesian tree for a multiobjective function of the NK random
EBNA_PLS_MPC_NKRandom EXAMPLE 16:
SOURCE CODE
function [ListFactorsCard] = FindListCard(ListFactors,Card)
% [ListFactorsCard] = FindListCard(ListFactors,Card)
% FindListCard:  For each factor of variables gives the corresponding
%                accumulate cardinality
% INPUT:
% ListFactors: Each  cell  {i} stores the variables in the factor
% Card: Cardinality of the variables
% OUTPUT:
% ListFactorsCard: For each factor of variables stores the corresponding
%                  accumulate cardinality
%
% Last version 8/26/2008. Roberto Santana (roberto.santana@ehu.es)
for i=1:size(ListFactors,2)
 ListFactorsCard{i} = FindAccCard(size(ListFactors{i},2),Card(ListFactors{i}));
end