Description of CreateFibbInitConf
Home > Mateda2.0 > functions > protein > CreateFibbInitConf.m
CreateFibbInitConf
PURPOSE
Translates the vector to the positions in the grid
SYNOPSIS
function[Sj] = CreateFibbInitConf(n)
DESCRIPTION
Translates the vector to the  positions in the grid
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
GaussianMultivariate_OfflineHPProtein EXAMPLE 12: Multivariate Gaussian EDA for the Offline HP Model continuous function
GaussianNetwork_OfflineHPProtein EXAMPLE 8: Gaussian network for the Offline HP Model continuous function
GaussianUMDA_OfflineHPProtein EXAMPLE 7: Gaussian UMDA for the Offline HP Model continuous function
MixtureGaussianEDAs_OfflineHP EXAMPLE 14: Mixtures of full Gaussian distributions
SOURCE CODE
function[Sj] =  CreateFibbInitConf(n)
%Translates the vector to the  positions in the grid
Si = [1];
Sj = [0];
for i=2:n
  aux = Sj;
  Sj = [Si,Sj];
  Si = aux;
end